// <auto-generated />
namespace WebAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class changesToDb : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changesToDb));
        
        string IMigrationMetadata.Id
        {
            get { return "202203160043163_changesToDb"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
